// src/lib/components/page-header.svelte
<script lang="ts">
  import { Bell } from "lucide-svelte";
  import {
    Button,
    DropdownMenu,
    DropdownMenuItem,
    SidebarTrigger,
  } from "$lib/components/ui";
  import SearchDialog from "./search-dialog.svelte";
  import ThemeToggle from "./theme-toggle.svelte";

  interface Props {
    searchPlaceholder?: string;
    notifications?: Array<{
      title: string;
      description: string;
    }>;
    children?: any;
  }

  let {
    searchPlaceholder = "Search...",
    notifications = [],
    children,
  }: Props = $props();
</script>

<header
  class="sticky top-0 z-10 flex items-center justify-between border-b bg-background/95 px-6 py-4 backdrop-blur supports-[backdrop-filter]:bg-background/60"
>
  <div class="flex items-center gap-3">
    <SidebarTrigger />
    <SearchDialog placeholder={searchPlaceholder} />
  </div>
  <div class="flex items-center gap-2">
    <ThemeToggle />

    {#if notifications.length > 0}
      <DropdownMenu>
        {#snippet trigger()}
          <Button variant="ghost" size="icon" class="relative">
            <Bell class="size-5" />
            <span
              class="absolute right-1.5 top-1.5 size-2 rounded-full bg-primary"
            ></span>
          </Button>
        {/snippet}

        {#snippet children()}
          {#each notifications as notification}
            <DropdownMenuItem>
              <div class="flex flex-col gap-1">
                <p class="font-medium">{notification.title}</p>
                <p class="text-sm text-muted-foreground">
                  {notification.description}
                </p>
              </div>
            </DropdownMenuItem>
          {/each}
        {/snippet}
      </DropdownMenu>
    {:else}
      <Button variant="ghost" size="icon" class="relative" disabled>
        <Bell class="size-5" />
      </Button>
    {/if}

    {@render children?.()}
  </div>
</header>

// nextjs-backup/components/page-header.tsx
"use client"

import { SidebarTrigger } from "@/components/ui/sidebar"
import { Button } from "@/components/ui/button"
import { Bell } from "lucide-react"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { SearchDialog } from "@/components/search-dialog"
import { ThemeToggle } from "@/components/theme-toggle"
import type { ReactNode } from "react"

interface PageHeaderProps {
  searchPlaceholder?: string
  notifications?: Array<{
    title: string
    description: string
  }>
  children?: ReactNode
}

export function PageHeader({ searchPlaceholder = "Search...", notifications = [], children }: PageHeaderProps) {
  return (
    <header className="sticky top-0 z-10 flex items-center justify-between border-b bg-background/95 px-6 py-4 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="flex items-center gap-3">
        <SidebarTrigger />
        <SearchDialog placeholder={searchPlaceholder} />
      </div>
      <div className="flex items-center gap-2">
        <ThemeToggle />
        {notifications.length > 0 && (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="relative">
                <Bell className="size-5" />
                <span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-primary" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-80">
              {notifications.map((notification, index) => (
                <DropdownMenuItem key={index}>
                  <div className="flex flex-col gap-1">
                    <p className="font-medium">{notification.title}</p>
                    <p className="text-sm text-muted-foreground">{notification.description}</p>
                  </div>
                </DropdownMenuItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>
        )}
        {children}
      </div>
    </header>
  )
}
